# Dify 服务器配置
dify_base_url: "http://localhost:8088/v1/"
dify_api_key: "dataset-ZsrVBy9Q7p01T0ZwTbM8nuvD"

# 日志配置
log_level: "INFO"
log_file: "logs/dify-mcp-server.log"

# MCP 服务器配置
mcp_server_name: "dify-rag-mcp"
mcp_server_version: "0.1.0"

# 开发环境配置
debug: false
test_mode: false

# HTTP 客户端配置
http_timeout: 30
http_retries: 3